on:
  push:
  pull_request:

name: check

jobs:
  check:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      #- name: Install Codecov
      #  run: sudo pip install codecov

      - name: where are we?
        run: pwd   
        
      - name: what is in here?
        run: ls
      
      - name: create build directory
        run: | 
              pwd
              mkdir build
              cd build
              pwd
        
      - name: where are we?
        run: pwd   
        
      - name: what is in here?
        run: ls   
        
      - name: what is up there?
        run: ls ..
        
      - name: cmake          
        env:
          CC: gcc
          CXX: gcc
        run: cmake .. 

      - name: build with cmake
        env:
          CC: gcc
          CXX: gcc
        run: cmake --build .

      - name: run
        run: ./arc_evo --test

     
      #- name: Measure codecov 1
       # run: ./get_code_cov.sh

      #- name: Measure codecov 2
       # run: codecov

      #- name: Measure codecov 3
       # run: bash <(curl -s https://codecov.io/bash)

