on:
  push:
  pull_request:

name: check

jobs:
  check:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Install Codecov
        run: sudo pip install codecov

      - name: create build directory
        run: mkdir build
        
      - name: enter build directory
        run: cd build   
        
      - name: list above build directory
        run: ls ..  
        
      - name: cmake
        run: cmake ..

      - name: build with cmake
        run: cmake --build .

      - name: run
        run: ./arc_evo --test

     
      #- name: Measure codecov 1
       # run: ./get_code_cov.sh

      #- name: Measure codecov 2
       # run: codecov

      #- name: Measure codecov 3
       # run: bash <(curl -s https://codecov.io/bash)

